### ISSUE TITLE
授权问题

### ISSUE THREAD

**Issue by mfkwfc** [chunbo007/wechat-mp#18]
问题1. 前端点击复制连接报错。
<img width="1563" alt="image" src="https://github.com/user-attachments/assets/782138c1-d1b0-4da9-9fa4-4d75381a887b">
问题2. 
<img width="585" alt="image" src="https://github.com/user-attachments/assets/accadbad-9074-4d77-9415-8fe8bf904780">
在点击复制连接后，打开会提示  请确认授权入口页所在域名，
解决方案：复制的地址应该是当前系统的地址， 用户打开系统地址后，自动跳到mp.weixin.qq.com 就不会报错了。

**Comment by mfkwfc** [comment]
项目很棒，晚一点有空我也可以解决，然后pr过去。

**Comment by chunbo007** [comment]
> 问题1. 前端点击复制连接报错。 <img alt="image" width="1563" src="https://private-user-images.githubusercontent.com/1892662/358989535-782138c1-d1b0-4da9-9fa4-4d75381a887b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjUzMjcsIm5iZiI6MTcyNDA2NTAyNywicGF0aCI6Ii8xODkyNjYyLzM1ODk4OTUzNS03ODIxMzhjMS1kMWIwLTRkYTktOWZhNC00ZDc1MzgxYTg4N2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTA1NzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2RlOGQ4NmRjNDdmZWFhNmU3Mzg2ZDAxY2NjNmEyMDgwYTEyZDU4NmJiYTRmM2Y1OTJjYWNiZDBiMmQxZTdkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eySO0NUPIFfhnowBS9xjaskMwuejkh6od0Zd3b2zGW4"> 问题2. <img alt="image" width="585" src="https://private-user-images.githubusercontent.com/1892662/358988912-accadbad-9074-4d77-9415-8fe8bf904780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjUzMjcsIm5iZiI6MTcyNDA2NTAyNywicGF0aCI6Ii8xODkyNjYyLzM1ODk4ODkxMi1hY2NhZGJhZC05MDc0LTRkNzctOTQxNS04ZmU4YmY5MDQ3ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTA1NzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWI5MDQxOWMwMmE0ZWUwZDFmYThkYjU4NzJjNjUzMjg2OWEyNGY5Mzg2ODNhZDYxYjM2MTdjNjAyOWFjZTk3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eFe8cc_IEDbjmW_-3s17h0LsXAi3p9W49NOJ_-DfmXM"> 在点击复制连接后，打开会提示 请确认授权入口页所在域名， 解决方案：复制的地址应该是当前系统的地址， 用户打开系统地址后，自动跳到mp.weixin.qq.com 就不会报错了。

得提前在平台设置好发起登录的域名URL，直接打开是不允许的，必须由配置的URL点击a链接。
这个功能其实只是测试用的，正式使用的时候最好是自己拿取token在自己的项目中生成授权链接
