### ISSUE TITLE
授权商户的refresh_token为空字符串

### ISSUE THREAD

**Issue by gitee1** [chunbo007/wechat-mp#4]
项目中现有的逻辑，每次拿到的授权商户的refresh_token都为空字符串。根据[微信开放社区](https://developers.weixin.qq.com/community/develop/doc/000e2a3c914810cc886b5aa4a56c00?_at=1648193591626&jumpto=comment&commentid=00088c2e4f45a0b1966b91543560)内的相关讨论信息发现，需要在授权的回调中调用[获取刷新令牌](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/ticket-token/getAuthorizerRefreshToken.html)接口才可以得到refresh_token

**Comment by chunbo007** [comment]
> 项目中现有的逻辑，每次拿到的授权商户的refresh_token都为空字符串。根据[微信开放社区](https://developers.weixin.qq.com/community/develop/doc/000e2a3c914810cc886b5aa4a56c00?_at=1648193591626&jumpto=comment&commentid=00088c2e4f45a0b1966b91543560)内的相关讨论信息发现，需要在授权的回调中调用[获取刷新令牌](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/ticket-token/getAuthorizerRefreshToken.html)接口才可以得到refresh_token

什么场景下需要使用refresh_token，原始报文里能看到refresh_token吗？

**Comment by gitee1** [comment]
> > 项目中现有的逻辑，每次拿到的授权商户的refresh_token都为空字符串。根据[微信开放社区](https://developers.weixin.qq.com/community/develop/doc/000e2a3c914810cc886b5aa4a56c00?_at=1648193591626&jumpto=comment&commentid=00088c2e4f45a0b1966b91543560)内的相关讨论信息发现，需要在授权的回调中调用[获取刷新令牌](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/ticket-token/getAuthorizerRefreshToken.html)接口才可以得到refresh_token
> 
> 什么场景下需要使用refresh_token，原始报文里能看到refresh_token吗？

1、就是拿不到authorizers表的refreshtoken字段，这个字段没有的话，授权小程序的版本管理什么的都没法进行
2、原始报文里面的refresh_token字段就是为空字符串；

**Comment by chunbo007** [comment]
> > > 项目中现有的逻辑，每次拿到的授权商户的refresh_token都为空字符串。根据[微信开放社区](https://developers.weixin.qq.com/community/develop/doc/000e2a3c914810cc886b5aa4a56c00?_at=1648193591626&jumpto=comment&commentid=00088c2e4f45a0b1966b91543560)内的相关讨论信息发现，需要在授权的回调中调用[获取刷新令牌](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/ticket-token/getAuthorizerRefreshToken.html)接口才可以得到refresh_token
> > 
> > 
> > 什么场景下需要使用refresh_token，原始报文里能看到refresh_token吗？
> 
> 1、refresh_token为空，就导致authorizers表的refreshtoken字段无值， 后续授权小程序的版本管理什么的都没法进行 2、原始报文里面的refresh_token字段就是为空字符串；

这个问题终于被我遇到了，之前用code换过token的没问题，所以我这里一直重现不出来。新授权的会有问题，已修复
