### ISSUE TITLE
npm安装 npm install --production 提示找不到app.json

### ISSUE THREAD

**Issue by miaomiaojianglove** [chunbo007/wechat-mp#5]
![image](https://github.com/chunbo007/wechat-mp/assets/28811199/3d496811-b58f-46f7-a3fb-7b5cd61c4819)
![image](https://github.com/chunbo007/wechat-mp/assets/28811199/3d496811-b58f-46f7-a3fb-7b5cd61c4819)

**Comment by chunbo007** [comment]
> ![image](https://private-user-images.githubusercontent.com/28811199/333538630-3d496811-b58f-46f7-a3fb-7b5cd61c4819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDQzMjQsIm5iZiI6MTcxNjU0NDAyNCwicGF0aCI6Ii8yODgxMTE5OS8zMzM1Mzg2MzAtM2Q0OTY4MTEtYjU4Zi00NmY3LWEzZmItN2I1Y2Q2MWM0ODE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA5NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NWRmMzRlNzZiMjgyZDY3NjVjMTQyMGQ0YThjMDI3NzI0NTE5MDFmYjljMzA0MjQ5NzZlZTVlZWM4ZTJmMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MvLwsZMmEpzSv54L7qZqGjk7bnTRH06Z525j4wQmJ6Y) ![image](https://private-user-images.githubusercontent.com/28811199/333538630-3d496811-b58f-46f7-a3fb-7b5cd61c4819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDQzMjQsIm5iZiI6MTcxNjU0NDAyNCwicGF0aCI6Ii8yODgxMTE5OS8zMzM1Mzg2MzAtM2Q0OTY4MTEtYjU4Zi00NmY3LWEzZmItN2I1Y2Q2MWM0ODE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA5NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NWRmMzRlNzZiMjgyZDY3NjVjMTQyMGQ0YThjMDI3NzI0NTE5MDFmYjljMzA0MjQ5NzZlZTVlZWM4ZTJmMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MvLwsZMmEpzSv54L7qZqGjk7bnTRH06Z525j4wQmJ6Y)

进到front目录下再执行

**Comment by miaomiaojianglove** [comment]
![image](https://github.com/chunbo007/wechat-mp/assets/28811199/03b0aa0c-dfc0-45df-bea1-0972428a762c)
貌似还是有问题老哥

**Comment by chunbo007** [comment]
> ![image](https://private-user-images.githubusercontent.com/28811199/333555403-03b0aa0c-dfc0-45df-bea1-0972428a762c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDcwNTYsIm5iZiI6MTcxNjU0Njc1NiwicGF0aCI6Ii8yODgxMTE5OS8zMzM1NTU0MDMtMDNiMGFhMGMtZGZjMC00NWRmLWJlYTEtMDk3MjQyOGE3NjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDEwMzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NzJkZmY3ZTM5Y2MxZmU4Y2Y1OTM5ZDlmZWRlZmU3MjY4ZjdlNDQyNDYxZjRiOWQ2ZjY0NWZmZmNkZWVlNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eayt8A8qexx59NszZOaxOjbeE4z180yZljlxwI4B-4Y) 貌似还是有问题老哥

加我V远程处理吧：chunboo

**Comment by chunbo007** [comment]
> ![image](https://private-user-images.githubusercontent.com/28811199/333555403-03b0aa0c-dfc0-45df-bea1-0972428a762c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDcwNTYsIm5iZiI6MTcxNjU0Njc1NiwicGF0aCI6Ii8yODgxMTE5OS8zMzM1NTU0MDMtMDNiMGFhMGMtZGZjMC00NWRmLWJlYTEtMDk3MjQyOGE3NjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDEwMzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NzJkZmY3ZTM5Y2MxZmU4Y2Y1OTM5ZDlmZWRlZmU3MjY4ZjdlNDQyNDYxZjRiOWQ2ZjY0NWZmZmNkZWVlNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eayt8A8qexx59NszZOaxOjbeE4z180yZljlxwI4B-4Y) 貌似还是有问题老哥

把package.json里的"eslint": "^7.0.0", 删掉再试，还是不行加我V：chunboo 远程看一下吧

**Comment by miaomiaojianglove** [comment]
> > ![image](https://private-user-images.githubusercontent.com/28811199/333555403-03b0aa0c-dfc0-45df-bea1-0972428a762c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDcwNTYsIm5iZiI6MTcxNjU0Njc1NiwicGF0aCI6Ii8yODgxMTE5OS8zMzM1NTU0MDMtMDNiMGFhMGMtZGZjMC00NWRmLWJlYTEtMDk3MjQyOGE3NjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDEwMzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NzJkZmY3ZTM5Y2MxZmU4Y2Y1OTM5ZDlmZWRlZmU3MjY4ZjdlNDQyNDYxZjRiOWQ2ZjY0NWZmZmNkZWVlNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eayt8A8qexx59NszZOaxOjbeE4z180yZljlxwI4B-4Y) 貌似还是有问题老哥
> 
> 把package.json里的"eslint": "^7.0.0", 删掉再试，还是不行加我V：chunboo 远程看一下吧

好的 感谢 大佬帮我跑起来我请你喝咖啡[手动滑稽]

**Comment by miaomiaojianglove** [comment]
死活无法部署[捂脸]
