### ISSUE TITLE
wxcallback_forward表url字段长度

### ISSUE THREAD

**Issue by gitee1** [chunbo007/wechat-mp#7]
wxcallback_forward表的url长度应该设置更长点，我这边遇到了url太长，导致写不进去数据的问题，直接导致wechat的IndexController的index方法抛出异常

**Comment by chunbo007** [comment]
> wxcallback_forward表的url长度应该设置更长点，我这边遇到了url太长，导致写不进去数据的问题，直接导致wechat的IndexController的index方法抛出异常

wxcallback_forward的url是转发地址，目前是varchar(255)还不够吗？你说的或许是response？
