### ISSUE TITLE
install.sql 插入管理员默认值有误

### ISSUE THREAD

**Issue by rangocc** [chunbo007/wechat-mp#8]
install.sql 插入管理员信息语句有误  create_time update_time 类型为int  
插入语句默认值'2024-01-18 23:17:23', '2024-01-13 23:50:17'

**Comment by chunbo007** [comment]
> install.sql 插入管理员信息语句有误 create_time update_time 类型为int 插入语句默认值'2024-01-18 23:17:23', '2024-01-13 23:50:17'

感谢反馈，已更新sql
