### ISSUE TITLE
线上部署无法登陆

### ISSUE THREAD

**Issue by lsa620620** [chunbo007/wechat-mp#9]
![微信图片_20240626101955](https://github.com/chunbo007/wechat-mp/assets/165749337/b396b28b-57ec-40cf-91ad-c011b033885b)
请问在线模式在部署时还须要改哪里？
请求的后台接口好像少了一个
http://user.360ruyu.cn:8001/auth/login
http://user.360ruyu.cn:8001/admin/auth/login

**Comment by chunbo007** [comment]
Nginx改了吗

**Comment by lsa620620** [comment]
已找出问题缺少.env.production文件
